# Generated by Django 4.1.13 on 2025-04-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='foto')),
                ('keterangan', models.TextField()),
                ('tanggal', models.TimeField(auto_now=True)),
            ],
        ),
    ]
