# Generated by Django 4.1.13 on 2025-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_edu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='foto')),
                ('keterangan', models.TextField()),
                ('tanggal', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='edu',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
